name: Python Autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose test set
        required: true
        type: choice
        default: all
        options:
          - smoke
          - regression
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest --alluredir=allure-results
        continue-on-error: true
      - name: Run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -m smoke --alluredir=allure-results
        continue-on-error: true
      - name: Run regression tests
        if: "github.event.inputs.deployment_target == 'regression'"
        run: pytest -m regression --alluredir=allure-results
        continue-on-error: true
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Install Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz
          tar -xzvf allure-2.24.1.tgz
          sudo mv allure-2.24.1 /opt/allure
          export PATH=/opt/allure/bin:$PATH
      - name: Generate Allure report
        run: allure generate allure-results --clean
      - name: Publish Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 1
